# Generated by Django 5.0.4 on 2024-04-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "param_name",
                    models.CharField(
                        max_length=64, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("param_value", models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Timestamps",
            fields=[
                (
                    "param_name",
                    models.CharField(
                        max_length=64, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="author",
            name="last_updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="ShortUpdateTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.author"
                    ),
                ),
            ],
        ),
    ]
