# Generated by Django 5.0.4 on 2024-04-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_settings_timestamps_alter_author_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.AlterModelOptions(
            name="authoralias",
            options={
                "verbose_name": "Псевдоним автора",
                "verbose_name_plural": "Псевдонимы автора",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Кафедра", "verbose_name_plural": "Кафедры"},
        ),
        migrations.AlterModelOptions(
            name="emailsubscriber",
            options={
                "verbose_name": "Подписчик на обновления",
                "verbose_name_plural": "Подписчики на обновления",
            },
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Факультет", "verbose_name_plural": "Факультеты"},
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={"verbose_name": "Публикация", "verbose_name_plural": "Публикации"},
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={
                "verbose_name": "Параметр системы",
                "verbose_name_plural": "Параметры системы",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
    ]
