# Generated by Django 5.0.4 on 2024-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_author_options_alter_authoralias_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="author",
            name="library_primary_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="authoralias",
            name="alias",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=48),
        ),
    ]
