# Generated by Django 5.0.4 on 2024-04-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_author_department_alter_author_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.department",
                verbose_name="Кафедра",
            ),
        ),
    ]
