# Generated by Django 5.0.4 on 2024-04-29 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_publication_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
