# Generated by Django 5.0.4 on 2024-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_author_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=48, unique=True, verbose_name="Название"),
        ),
    ]
