# Generated by Django 6.0.2 on 2026-02-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_emailsubscriber_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="sort_order",
            field=models.IntegerField(
                default=0, verbose_name="Поле сортировки (год публикации)"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.department",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="param_value",
            field=models.CharField(max_length=1024, verbose_name="Настройка"),
        ),
    ]
